# Generated by Django 5.2.8 on 2025-12-08 12:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchStatusUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Optional geo/location text', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispatch Status Update',
                'verbose_name_plural': 'Dispatch Status Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogisticsAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logistics Agent',
                'verbose_name_plural': 'Logistics Agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('Keke', 'Keke'), ('OTHER', 'Other')], default='MOTORCYCLE', max_length=20)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('capacity_description', models.CharField(blank=True, help_text='e.g. 100kg or 2 crates', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_code', models.CharField(blank=True, help_text='Optional external reference or tracking code', max_length=120)),
                ('pickup_address', models.TextField(blank=True)),
                ('dropoff_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('estimated_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.DateTimeField(blank=True, null=True)),
                ('proof_of_delivery_url', models.URLField(blank=True, help_text='Photo or signature URL')),
                ('receiver_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional delivery cost', max_digits=10, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-created_at'],
            },
        ),
    ]
