# Generated by Django 5.2.8 on 2025-12-08 12:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(blank=True, help_text='Optional farm or business name', max_length=255)),
                ('contact_name', models.CharField(help_text="Farmer's full name", max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('farm_type', models.CharField(choices=[('CROPS', 'Crops'), ('LIVESTOCK', 'Livestock'), ('POULTRY', 'Poultry'), ('AQUACULTURE', 'Aquaculture'), ('MIXED', 'Mixed'), ('OTHER', 'Other')], default='CROPS', max_length=20)),
                ('farm_size', models.DecimalField(blank=True, decimal_places=2, help_text='Size (in hectares or specify unit in notes)', max_digits=8, null=True)),
                ('years_of_experience', models.PositiveSmallIntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('profile_image', models.URLField(blank=True, help_text='Cloud URL for profile image', null=True)),
                ('verified', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('verification_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional free-form metadata', null=True)),
                ('user', models.OneToOneField(blank=True, help_text='Optional link to a User account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farmer',
                'verbose_name_plural': 'Farmers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Document type or name', max_length=255)),
                ('file_url', models.URLField(help_text='Cloud storage URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Document',
                'verbose_name_plural': 'Farmer Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Product name (e.g., Maize, Eggs)', max_length=255)),
                ('category', models.CharField(blank=True, help_text='Optional product category', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bag', 'Bag'), ('crate', 'Crate'), ('litre', 'Litre'), ('piece', 'Piece'), ('bird', 'Bird'), ('ton', 'Ton'), ('other', 'Other')], default='kg', max_length=20)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_available', models.DecimalField(decimal_places=3, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('harvest_date', models.DateField(blank=True, help_text='Optional harvest/packaging date', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('images', models.JSONField(blank=True, help_text='List of image URLs', null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='farmers.farmer')),
            ],
            options={
                'verbose_name': 'Farmer Product',
                'verbose_name_plural': 'Farmer Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('bag', 'Bag'), ('crate', 'Crate'), ('litre', 'Litre'), ('piece', 'Piece'), ('bird', 'Bird'), ('ton', 'Ton'), ('other', 'Other')], default='kg', max_length=20)),
                ('supply_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=10)),
                ('quality_notes', models.TextField(blank=True)),
                ('received_by', models.CharField(blank=True, help_text='Name of the receiver at pickup/warehouse', max_length=255)),
                ('reference_code', models.CharField(blank=True, help_text='Optional external reference', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_records', to='farmers.farmer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_records', to='farmers.farmerproduct')),
            ],
            options={
                'verbose_name': 'Supply Record',
                'verbose_name_plural': 'Supply Records',
                'ordering': ['-supply_date'],
            },
        ),
        migrations.AddIndex(
            model_name='farmerproduct',
            index=models.Index(fields=['farmer', 'title'], name='farmers_far_farmer__6abc95_idx'),
        ),
        migrations.AddIndex(
            model_name='supplyrecord',
            index=models.Index(fields=['farmer', 'product', 'status'], name='farmers_sup_farmer__078d47_idx'),
        ),
    ]
